using System.Collections.Generic;

namespace Models.Helper
{
    public static class AccommodationCatalog
    {
        private static readonly IReadOnlyList<string> _options = new List<string>
        {
            "Select Your Hotel",
            "Not Sure Yet",
            "Not on the List",
            "1207 Boutique Hotel - Antalya 2",
            "Adahan Hotel - Antalya 3",
            "Adalya Port Hotel - Antalya 2",
            "Adam Eve Hotel - Belek 2",
            "Address Residence - Antalya 3",
            "Adonis Hotel - Antalya 3",
            "Adora Golf Resort - Belek 5",
            "Akpalace Belek - Belek 5",
            "Akra Barut Hotel - Antalya 3",
            "Akra V Hotel - Antalya 3",
            "Altes Otel - Antalya 3",
            "Altis Resort Hotel & Spa - Belek 4",
            "Altos Apart Otel - Belek 2",
            "Alva Donna Exclusive Hotel & Spa - Bogazkent",
            "Antalya Inn Boutique Hotel - Antalya 2",
            "Armas Belek - Belek 1",
            "Aspen Hotel - Antalya 2",
            "Atelya Art Hotel - Antalya 2",
            "Avsar Boutique Hotel - Antalya 1",
            "Aydınbey Famous Resort - Bogazkent",
            "Azure Villas By Cornelia - Belek 3",
            "Bacchus Hostel - Antalya 2",
            "Barut Lara - Kundu 1",
            "Belconti Resort Hotel - Belek 2",
            "Belek Beach Resort - Bogazkent",
            "Belek Flash Otel - Belek 2",
            "Belek Park Hotel - Belek 2",
            "Belkon Hotel - Belek 5",
            "Bellis Deluxe Hotel - Belek 3",
            "Bilem High Class Hotel - Antalya 3",
            "Boss Boutique Hotel - Antalya 2",
            "C&H Hotels Türkevi - Antalya 2",
            "Calista Luxury Resort Hotel - Belek 3",
            "Camel Hostel - Antalya 2",
            "Candle Suites - Antalya 2",
            "Castle Boutique Hotel - Antalya 2",
            "Ceres Hotel Belek - Belek 2",
            "Cesars Temple De Luxe - Belek 1",
            "Char Me Boutique Hotel - Antalya 2",
            "Citrus Garden Hotel - Antalya 2",
            "Citrus Garden Hotel & Restaurant - Antalya 2",
            "City Live Hotel - Antalya 3",
            "Club Asteria Belek - Belek 5",
            "Club Hotel Falcon - Antalya 3",
            "Club Hotel Sera Deluxe - Lara",
            "Club Mega Saray Belek - Belek 5",
            "Club Prive By Rixos Belek - Belek 1",
            "Concorde De Luxe Resort - Kundu 2",
            "Cornelia De Luxe Resort Hotel - Belek 1",
            "Cornelia Diamond Golf Resort & Spa - Belek 3",
            "Crystal Family Resort & Spa - Bogazkent",
            "Crystal Paraiso Verde Resort - Bogazkent",
            "Crystal Tat Beach Golf Resort & Spa - Belek 5",
            "Crystal Waterworld Resort & Spa - Bogazkent",
            "Çenger Beach Resort & Spa - Manavgat",
            "Daima Resort - Kiris",
            "Dantel Pansiyon - Antalya 2",
            "Dedehan Pansiyon - Antalya 2",
            "Dedekonak Hostel - Antalya 2",
            "Deja Vu Hotel - Antalya 2",
            "Delight Deluxe Apartments - Antalya 2",
            "Delight Deluxe Boutique Hotel - Antalya 2",
            "Delphin Be Grand Resort - Kundu 1",
            "Delphin Diva Premiere - Kundu 2",
            "Delphin Imperial Lara - Kundu 2",
            "Dinç Otel Lara - Lara",
            "Dionis Hotels Resort & Spa - Bogazkent",
            "Duru Family Otel - Lara",
            "Duru Suites - Antalya 3",
            "Ela Quality Resort Hotel - Belek 3",
            "Elegance East Hotel - Antalya 2",
            "Elips Royal Hotel & Spa - Antalya 2",
            "Erdeniz Apart Hotel - Lara",
            "Erkal Pansiyon - Antalya 2",
            "Erken Konak Pansiyon - Antalya 2",
            "Esperanza Boutique Hotel - Lara",
            "Exporoyal Hotel - Antalya 2",
            "Fame Residence Lara & Spa - Kundu 2",
            "Febeach Resort & Spa - Belek 4",
            "Frankfurt Hotel - Antalya 2",
            "Gloria Golf Resort - Belek 1",
            "Gloria Serenity Resort - Belek 1",
            "Gloria Sports Arena - Belek 2",
            "Goodman Hotel & Bistro - Antalya 2",
            "Gözde Otel - Belek 2",
            "Granada Luxury Belek - Belek 2",
            "Grand Erken Hotel - Antalya 2",
            "Grand Park Lara - Kundu 2",
            "Grand Sancak Hotel - Antalya 3",
            "Green Beyza Hotel - Antalya 3",
            "Green Max Hotel - Belek 5",
            "Güral Premier Belek - Belek 2",
            "Gürtaş Hotel - Antalya 2",
            "Hadrian Gate Hotel - Antalya 2",
            "Held Hotel - Antalya 2",
            "Helene Apart Hotel - Lara",
            "Holiday Inn Lara - Lara",
            "Hotel Baia Lara - Kundu 2",
            "Hotel Belek Palas - Belek 2",
            "Hotel Blue Sea Garden - Antalya 2",
            "Hotel Karyatit - Antalya 2",
            "Hotel Kaya Palazzo - Belek 4",
            "Hotel Kervansaray Lara Convention & Spa Center - Kundu 1",
            "Hotel Paris Antalya - Lara",
            "Hotel Riu Kaya Belek - Belek 4",
            "Hotel Su - Lara",
            "Hotel Twenty - Antalya 2",
            "Hun Club Hotel - Antalya 1",
            "IC Hotels Airport - Lara",
            "IC Hotels Santai Family Resort - Belek 5",
            "Innvista Hotels Belek - Belek 4",
            "Kaleici Eliza Hotel - Antalya 2",
            "Kaleiçi Lodge Hotel - Antalya 2",
            "Kaleiçi Otel - Antalya 2",
            "Kaleiçi Ozkavak Hotel - Antalya 2",
            "Kauçuk Residence - Antalya 2",
            "Kempinski Hotel The Dome - Belek 4",
            "Kervansaray Kundu Beach Hotel - Kundu 2",
            "Kirman Hotels Belazur Resort & Spa - Bogazkent",
            "Konukzade 36 Hotel - Antalya 2",
            "Kosa Butik Otel - Antalya 2",
            "Kurt Hotel - Belek 2",
            "La Boutique Hotel - Antalya 3",
            "La Paloma Hotel - Antalya 2",
            "Lale Apart Otel - Antalya 3",
            "Lara Atalla Hotel - Antalya 3",
            "Lara Diamond Hotel - Lara",
            "Lara Family Club Suite - Kundu 2",
            "Lara Hadrianus Hotel - Lara",
            "Lara Hotel - Lara",
            "Lara Kapris Otel - Lara",
            "Lara Konakları - Antalya 3",
            "Lara Park Hotel - Lara",
            "Lara World Hotel - Lara",
            "Lazer Pansiyon - Antalya 2",
            "Let stay Boutique Hotel - Antalya 3",
            "Letoonia Golf Resort - Belek 1",
            "Liberty Hotels Lara - Kundu 2",
            "Limak Arcadia Hotel & Resort - Belek 2",
            "Limak Atlantis De Luxe Hotel & Resort - Belek 1",
            "Limak Lara De Luxe Hotel & Resort - Kundu 2",
            "Loft 1502 - Antalya 3",
            "Luna Otel - Antalya 2",
            "Lygos Hotel - Lara",
            "Madi Hotel Lara - Antalya 3",
            "Marina Hostel - Antalya 2",
            "Maritim Pine Beach Resort - Belek 1",
            "Marka Hotel - Antalya 2",
            "Mavi & Ani Pension - Antalya 2",
            "Maxx Royal - Belek 2",
            "Maya World Hotel Belek - Belek 4",
            "MC Donalds - Antalya 2",
            "Melas Hotel Lara - Kundu 2",
            "Mholiday Hotels Belek - Bogazkent",
            "Mia Boutique Hotel - Antalya 2",
            "Minyon Hotel - Antalya 2",
            "Miracle Resort Hotel - Kundu 1",
            "Monopoly Mansions - Antalya 2",
            "Movie Life Hotel - Antalya 3",
            "München Pansiyon - Antalya 2",
            "Nasa Flora Otel - Antalya 3",
            "Nazar Beach Hotel - Lara",
            "Nebilüx Hotel - Antalya 3",
            "Ninova Hotel - Antalya 2",
            "Nirvana Club - Belek 2",
            "Odile Konak - Antalya 2",
            "Otantik Boutique Hotel - Antalya 2",
            "Otel Anfora - Belek 2",
            "Özmen Pansiyon - Antalya 2",
            "Öztürk Otel - Antalya 2",
            "Palm House 17 - Antalya 2",
            "Paloma Grida Resort & Spa Hotel - Belek 2",
            "Papillon Ayscha Hotel Resort & SPA - Belek 1",
            "Papillon Belvil - Belek 4",
            "Papillon Zeugma Relaxury - Belek 1",
            "Pinus Apart Otel - Antalya 3",
            "Port Nature Luxury Resort Hotel & Spa - Bogazkent",
            "Prima Hotel - Antalya 3",
            "Prime Boutique Hotel - Antalya 2",
            "Puding Marina Residence - Antalya 2",
            "Queen Ra Hotel - Antalya 3",
            "Ramada Resort Lara - Kundu 2",
            "Raymar Hotels & Resorts - Manavgat",
            "Regnum Carya Golf & Spa Resort - Belek 4",
            "Rixos Premium Belek - Belek 1",
            "Robinson Club Nobilis - Belek 1",
            "Role Street Hostel - Antalya 2",
            "Royal Atalla Hotel - Antalya 2",
            "Royal Holiday Palace - Kundu 2",
            "Royal Seginus Hotel - Kundu 2",
            "Royal Wings Hotel - Kundu 2",
            "Sabah Pansiyon - Antalya 2",
            "Sarp Hotels Belek - Belek 4",
            "Saturn Palace Resort - Kundu 2",
            "Sayılan Hotel - Antalya 3",
            "Selectum Luxury Resort - Belek 3",
            "Selge Hotel - Side",
            "Sensimar Belek Resort & Spa Hotel - Bogazkent",
            "Sensitive Premium Resort Spa - Bogazkent",
            "Sentido Zeynep Golf & Spa - Belek 4",
            "Sentido Zeynep Resort - Belek 4",
            "Seven Stars Exclusive Hotel - Antalya 3",
            "Sherwood Breezes Resort - Kundu 2",
            "Sherwood Dreams Resort - Bogazkent",
            "Sherwood Prize Hotel - Antalya 3",
            "Shiluh Apart - Antalya 2",
            "Siam Elegance Hotels & Spa - Bogazkent",
            "Sirene Belek Hotel - Belek 5",
            "Spice Hotel & Spa - Belek 2",
            "Sueno Hotels Deluxe Belek - Belek 3",
            "Sueno Hotels Golf Belek - Belek 3",
            "Sun Rise Hotel - Antalya 2",
            "Susesi Luxury Resort - Belek 3",
            "Şato Otel Lara - Antalya 3",
            "Teos Hotel - Antalya 3",
            "Tepe Hotel - Antalya 3",
            "The Land Of Legends Thema Park - Belek 4",
            "The Lifeco Antalya - Antalya 3",
            "The Marmara Hotel Antalya - Antalya 3",
            "The Prime Garden Hotel - Belek 5",
            "The Suite Apart Hotel - Antalya 2",
            "Throne Seagate Belek Hotel - Bogazkent",
            "Titanic Beach Resort Hotel - Kundu 1",
            "Titanic Deluxe Belek Beach - Belek 5",
            "Titanic Deluxe Golf Belek - Belek 5",
            "Tourist Hotel - Lara",
            "Tria Hotel Antalya - Antalya 3",
            "TUI Magic Life Masmavi - Belek 4",
            "Tui Fun & Sun Club Belek - Belek 1",
            "Tui Magic Life Waterworld - Belek 3",
            "Urcu Butik Hotel - Antalya 2",
            "Ümit Hotel - Antalya 3",
            "Venezia Palace Deluxe Resort - Kundu 2",
            "Vera Verde Resort Belek - Bogazkent",
            "Villa Belek Resort - Belek 4",
            "Villa Mavi Luxury Apart - Antalya 2",
            "Villa Perla Hotel - Antalya 2",
            "Villa Tulipan - Antalya 2",
            "Voyage Belek Golf & Spa - Belek 2",
            "Voyage Sorgun - Manavgat",
            "White Garden Pansiyon - Antalya 2",
            "Wind Of Lara Hotel & Spa - Kundu 1",
            "Wise Hotel & Spa - Antalya 3",
            "Wow Kremlin Palace - Kundu 2",
            "Wow Topkapı Palace - Kundu 2",
            "Xanadu Resort Hotel - Belek 1"
        };

        public static IReadOnlyList<string> List() => _options;
    }
}
